apiVersion: v1
kind: Pod
metadata:
  name: dist-mq
  labels:
    role: dist-mq
spec:
  containers:
    - name: dist-mq
      image: docker.io/library/dist-mq:local
      imagePullPolicy: IfNotPresent
      args:
        - "-http-addr=0.0.0.0:8080"
        - "-raft-addr=0.0.0.0:9000"
        - "-raft"
      ports:
        - name: dist-mq
          containerPort: 8080
          protocol: TCP
        - name: distmq-raft
          containerPort: 9000
          protocol: TCP
  restartPolicy: Always
  